name: Metrics
on:
  # 毎日0時に更新
  schedule: [{cron: "0 0 * * *"}]
  # 手動実行
  workflow_dispatch:
  # mainブランチにプッシュされた時も実行
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: kalmlpv
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata
          
          plugin_languages: yes
          # plugin_languages_ignored: 
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
